db_file: "bot.db"

bot_url: "https://t.me/PocketManager_Bot"

messages:
  responses:
    start: "Для продолжения, авторизируйте бота в Pocket \n Для этого перейдите по ссылке: \n%s "
    already_authorized: "Пришлите свою ссылку для сохранения"
    unknown_command: "Неизвестная команда"
    link_saved: "Ссылка успешно сохранена!"
  error:
    default: "Произошла неизвестная ошибка."
    invalid_url:  "Это невалидная ссылка."
    unable_to_save: "Не удалось сохранить ссылку в Pocket. Попробуйте пожалуйста позже."